import {
  useAgentRulesStore,
  usePromptsStore,
  useSettingsStore,
  useShellStore,
  useSkillsStore,
} from "../../../shared/stores";

export function useWorkbenchStoresSnapshot() {
  const shell = {
    activeModule: useShellStore((state) => state.activeModule),
    setActiveModule: useShellStore((state) => state.setActiveModule),
    promptViewMode: useShellStore((state) => state.promptViewMode),
    setPromptViewMode: useShellStore((state) => state.setPromptViewMode),
    skillDetailTab: useShellStore((state) => state.skillDetailTab),
    setSkillDetailTab: useShellStore((state) => state.setSkillDetailTab),
    settingsCategory: useShellStore((state) => state.settingsCategory),
    setSettingsCategory: useShellStore((state) => state.setSettingsCategory),
    sidebarOpen: useShellStore((state) => state.mobileSidebarOpen),
    setSidebarOpen: useShellStore((state) => state.setMobileSidebarOpen),
    mobileDetailOpen: useShellStore((state) => state.mobileDetailOpen),
    setMobileDetailOpen: useShellStore((state) => state.setMobileDetailOpen),
  };

  const prompts = {
    prompts: usePromptsStore((state) => state.prompts),
    promptsLoading: usePromptsStore((state) => state.loading),
    selectedPromptId: usePromptsStore((state) => state.selectedPromptId),
    promptVersions: usePromptsStore((state) => state.versionsByPromptId),
    fetchPrompts: usePromptsStore((state) => state.fetchPrompts),
    selectPrompt: usePromptsStore((state) => state.selectPrompt),
    deletePrompt: usePromptsStore((state) => state.deletePrompt),
    createPrompt: usePromptsStore((state) => state.createPrompt),
    updatePrompt: usePromptsStore((state) => state.updatePrompt),
    fetchPromptVersions: usePromptsStore((state) => state.fetchVersions),
    restorePromptVersion: usePromptsStore((state) => state.restoreVersion),
    promptSelectedIds: usePromptsStore((state) => state.selectedIds),
    setPromptSelection: usePromptsStore((state) => state.setSelection),
    clearPromptSelection: usePromptsStore((state) => state.clearSelection),
    batchFavorite: usePromptsStore((state) => state.batchFavorite),
    batchMove: usePromptsStore((state) => state.batchMove),
    batchDelete: usePromptsStore((state) => state.batchDelete),
    promptBatchResult: usePromptsStore((state) => state.lastBatchResult),
  };

  const skills = {
    skills: useSkillsStore((state) => state.skills),
    skillsLoading: useSkillsStore((state) => state.loading),
    selectedSkillId: useSkillsStore((state) => state.selectedSkillId),
    fetchSkills: useSkillsStore((state) => state.fetchSkills),
    scanSkills: useSkillsStore((state) => state.scanSkills),
    selectSkill: useSkillsStore((state) => state.selectSkill),
    managerState: useSkillsStore((state) => state.managerState),
    managerLoading: useSkillsStore((state) => state.managerLoading),
    managerCalibrating: useSkillsStore((state) => state.managerCalibrating),
    managerMode: useSkillsStore((state) => state.managerMode),
    managerExpandedSkillId: useSkillsStore((state) => state.managerExpandedSkillId),
    managerMatrixFilter: useSkillsStore((state) => state.managerMatrixFilter),
    managerRowHints: useSkillsStore((state) => state.managerRowHints),
    usageAgentFilter: useSkillsStore((state) => state.usageAgentFilter),
    usageSourceFilter: useSkillsStore((state) => state.usageSourceFilter),
    usageEvidenceSourceFilter: useSkillsStore((state) => state.usageEvidenceSourceFilter),
    usageStatsLoading: useSkillsStore((state) => state.usageStatsLoading),
    usageStatsError: useSkillsStore((state) => state.usageStatsError),
    usageListSyncJob: useSkillsStore((state) => state.usageListSyncJob),
    usageDetailSyncJob: useSkillsStore((state) => state.usageDetailSyncJob),
    usageDetailCalls: useSkillsStore((state) => state.usageDetailCalls),
    usageDetailCallsTotal: useSkillsStore((state) => state.usageDetailCallsTotal),
    usageDetailCallsLoading: useSkillsStore((state) => state.usageDetailCallsLoading),
    usageDetailCallsError: useSkillsStore((state) => state.usageDetailCallsError),
    getManagerOperationsRows: useSkillsStore((state) => state.getManagerOperationsRows),
    loadManagerState: useSkillsStore((state) => state.loadManagerState),
    managerBatchLink: useSkillsStore((state) => state.managerBatchLink),
    managerBatchUnlink: useSkillsStore((state) => state.managerBatchUnlink),
    setManagerMode: useSkillsStore((state) => state.setManagerMode),
    setManagerExpandedSkillId: useSkillsStore((state) => state.setManagerExpandedSkillId),
    setManagerMatrixFilter: useSkillsStore((state) => state.setManagerMatrixFilter),
    clearManagerRowHint: useSkillsStore((state) => state.clearManagerRowHint),
    setUsageFilters: useSkillsStore((state) => state.setUsageFilters),
    refreshUsageStats: useSkillsStore((state) => state.refreshUsageStats),
    startListUsageSync: useSkillsStore((state) => state.startListUsageSync),
    dismissListUsageSyncJob: useSkillsStore((state) => state.dismissListUsageSyncJob),
    startDetailUsageSync: useSkillsStore((state) => state.startDetailUsageSync),
    loadUsageCalls: useSkillsStore((state) => state.loadUsageCalls),
    clearUsageDetail: useSkillsStore((state) => state.clearUsageDetail),
  };

  const agentRules = {
    agentAssets: useAgentRulesStore((state) => state.assets),
    agentTagsByAsset: useAgentRulesStore((state) => state.tagsByAsset),
    agentVersionsByAsset: useAgentRulesStore((state) => state.versionsByAsset ?? {}),
    agentConnections: useAgentRulesStore((state) => state.connections),
    agentRulesError: useAgentRulesStore((state) => state.lastActionError),
    selectedAssetId: useAgentRulesStore((state) => state.selectedAssetId),
    setSelectedAssetId: useAgentRulesStore((state) => state.setSelectedAssetId),
    clearAgentRulesError: useAgentRulesStore((state) => state.clearError),
    loadAgentModuleData: useAgentRulesStore((state) => state.loadModuleData),
    loadAgentConnections: useAgentRulesStore((state) => state.loadConnections),
    loadAgentVersions: useAgentRulesStore((state) => state.loadVersions),
    createAgentAsset: useAgentRulesStore((state) => state.createAsset),
    renameAgentAsset: useAgentRulesStore((state) => state.renameAsset),
    deleteAgentAsset: useAgentRulesStore((state) => state.deleteAsset),
    publishAgentVersion: useAgentRulesStore((state) => state.publishVersion),
    rollbackAgentRuleVersion: useAgentRulesStore((state) => state.rollbackVersion),
    refreshAgentAsset: useAgentRulesStore((state) => state.refreshAsset),
    runAgentDistribution: useAgentRulesStore((state) => state.runDistribution),
  };

  const settings = {
    workspaces: useSettingsStore((state) => state.workspaces),
    activeWorkspaceId: useSettingsStore((state) => state.activeWorkspaceId),
    settingsTargets: useSettingsStore((state) => state.targets),
    settingsConnections: useSettingsStore((state) => state.connections),
    dirty: useSettingsStore((state) => state.dirty),
    settingsLoading: useSettingsStore((state) => state.loading),
    loadAllSettings: useSettingsStore((state) => state.loadAll),
    loadSettingsConnections: useSettingsStore((state) => state.loadConnections),
    upsertTarget: useSettingsStore((state) => state.upsertTarget),
    deleteTarget: useSettingsStore((state) => state.deleteTarget),
    upsertConnection: useSettingsStore((state) => state.upsertConnection),
    deleteConnection: useSettingsStore((state) => state.deleteConnection),
    setDirty: useSettingsStore((state) => state.setDirty),
  };

  return { shell, prompts, skills, agentRules, settings };
}
